### ISSUE TITLE
manifest.json support

### ISSUE THREAD

**Issue by lorypelli** [zhuweiyou/vite-plugin-minify#4]
Is possible to have this also for manifest.json ?

**Comment by zhuweiyou** [comment]
Currently using `transformIndexHtml` hook, not support `manifest.json`.

**Comment by lorypelli** [comment]
> Currently using `transformIndexHtml` hook, not support `manifest.json`.

Is there another way to do manifest.json then?

**Comment by zhuweiyou** [comment]
You can try to read `dist/manifest.json`, use [buildEnd](https://rollupjs.org/guide/en/#buildend) or [closeBundle](https://rollupjs.org/guide/en/#closebundle) hook.

**Comment by lorypelli** [comment]
> You can try to read `dist/manifest.json`, use [buildEnd](https://rollupjs.org/guide/en/#buildend) or [closeBundle](https://rollupjs.org/guide/en/#closebundle) hook.

idk if I will be able to, this is why I chose this
